import gzip
import io
import textwrap

def html_to_c_gzip_array(html_content, array_name="index_ov2640_html_gz", define_name="index_ov2640_html_gz_len"):
    """
    Compresses HTML content using gzip and formats it into a C-style byte array.

    Args:
        html_content (str): The HTML string to be compressed.
        array_name (str): The name for the C const unsigned char array.
        define_name (str): The name for the C #define length constant.

    Returns:
        str: A string containing the C header file content.
    """
    
    html_bytes = html_content.encode('utf-8')
    buf = io.BytesIO()
    
    with gzip.GzipFile(fileobj=buf, mode='wb', mtime=0) as f:
        f.write(html_bytes)
    
    gzip_bytes = buf.getvalue()

    
    data_len = len(gzip_bytes)

    
    hex_list = [f"0x{b:02x}" for b in gzip_bytes]
    
    
    formatted_hex = []
    for i in range(0, data_len, 16):
        line = ", ".join(hex_list[i:i+16])
        
        formatted_hex.append(f"  {line},")
    
    if formatted_hex:
        last_line = formatted_hex[-1]
        formatted_hex[-1] = last_line.rstrip(',')

    array_body = "\n".join(formatted_hex)

    c_array_template = f"""\
// This file was automatically generated by a Python script
// Do NOT modify manually!

// --- Custom UI DEFINITION ---
#define {define_name} {data_len}

const unsigned char {array_name}[] = {{
{array_body}
}};

// --- DUMMY DEFINITIONS FOR OTHER MODELS (TO PREVENT COMPILATION ERRORS in app_httpd.cpp) ---
// Your sketch seems to check for OV3660 and OV5640, but you only provided one UI.
// We include these empty definitions to satisfy the compiler checks.
#define index_ov3660_html_gz_len 0
const unsigned char index_ov3660_html_gz[] = {{}};

#define index_ov5640_html_gz_len 0
const unsigned char index_ov5640_html_gz[] = {{}};
"""
    return c_array_template


html_input = textwrap.dedent("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ESP32-CAM | IoT Experiment 6</title>
    <style>
        :root {
            --bg: #f7f8fa;
            --card: #ffffff;
            --border: #e5e7eb;
            --accent: #5c6bc0; /* Darker pastel blue-violet */
            --accent-hover: #4e5aa1;
            --danger: #e57373; /* Slightly darker pastel red */
            --danger-hover: #d9534f;
            --success: #81c784; /* Soft green */
            --success-hover: #66bb6a;
            --warning: #ffb74d; /* Soft orange for unlock */
            --warning-hover: #ffa726;
            --text: #2d2d2d;
            --soft-text: #555;
            --shadow: 0 8px 24px rgba(0, 0, 0, 0.08);
            --radius: 16px;
            --transition: 0.25s ease;
            font-family: "Inter", "Poppins", sans-serif;
        }

        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        body {
            background: linear-gradient(160deg, #f3f2ff, #fafbff);
            color: var(--text);
            display: flex;
            justify-content: center;
            align-items: flex-start;
            min-height: 100vh;
            padding: 2rem;
        }

        .container {
            width: 100%;
            max-width: 740px;
            background: var(--card);
            border-radius: var(--radius);
            box-shadow: var(--shadow);
            padding: 2rem;
            text-align: center;
        }

        header {
            margin-bottom: 1.5rem;
        }

        header h1 {
            font-size: 1.6rem;
            color: var(--accent);
            margin-bottom: 0.2rem;
        }

        header h2 {
            font-size: 1.2rem;
            color: var(--accent-hover);
            margin-bottom: 0.8rem;
        }

        header p {
            color: var(--soft-text);
            font-size: 0.9rem;
            margin-bottom: 0.2rem;
        }
        
        .student-details {
            font-size: 1.1rem;
            color: var(--text);
            font-weight: 600;
        }

        .camera-frame {
            width: 100%;
            border-radius: var(--radius);
            overflow: hidden;
            border: 1px solid var(--border);
            background: #f3f4f6;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 360px;
            position: relative;
        }

        #stream {
            width: 100%;
            height: auto;
            display: none;
        }

        .controls {
            display: flex;
            justify-content: center;
            gap: 10px; 
            margin-top: 1.5rem;
            flex-wrap: wrap;
        }

        .btn {
            padding: 10px 20px;
            border: none;
            border-radius: var(--radius);
            font-size: 0.95rem;
            cursor: pointer;
            color: #fff;
            box-shadow: 0 3px 10px rgba(0, 0, 0, 0.1);
            transition: var(--transition);
        }

        .btn:disabled {
            opacity: 0.5;
            cursor: not-allowed;
        }

        .start { background: var(--accent); }
        .start:hover { background: var(--accent-hover); }

        .stop { background: var(--danger); }
        .stop:hover { background: var(--danger-hover); }

        .capture { background: var(--success); }
        .capture:hover { background: var(--success-hover); }

        .unlock { background: var(--warning); }
        .unlock:hover { background: var(--warning-hover); }

        .preview {
            margin-top: 2rem;
            background: var(--bg);
            padding: 1.5rem;
            border-radius: var(--radius);
            border: 1px solid var(--border);
            box-shadow: var(--shadow);
            display: none;
        }

        .preview h2 {
            font-size: 1.1rem;
            margin-bottom: 0.8rem;
            color: var(--accent);
        }

        .preview img {
            width: 100%;
            border-radius: var(--radius);
            border: 1px solid var(--border);
        }
        
        .alert-granted {
            margin-top: 1.5rem;
            padding: 15px;
            border-radius: var(--radius);
            background: var(--success);
            color: white;
            font-size: 1.1rem;
            font-weight: bold;
            display: none;
            box-shadow: 0 2px 8px rgba(129, 199, 132, 0.4);
        }
    </style>
</head>
<body>
    <main class="container">
        <header>
            <h1>Vishwakarma Institute of Information Technology</h1>
            <h2>IoT Experiment 6 – ESP32-CAM for Security</h2>
            <p class="student-details"><strong>Name:</strong> Name: </p>
            <p class="student-details"><strong>Roll No:</strong> Roll Number: </p>
        </header>

        <section class="camera">
            <div class="camera-frame">
                <img id="stream" src="" alt="Camera Stream">
            </div>

            <div class="controls">
                <button id="startBtn" class="btn start">Start</button>
                <button id="stopBtn" class="btn stop" disabled>Stop</button>
                <button id="captureBtn" class="btn capture" disabled>Capture</button>
                <button id="unlockBtn" class="btn unlock" disabled>Unlock Door</button>
            </div>
            
            <div id="accessGrantedAlert" class="alert-granted">
                Face Matched. ACCESS GRANTED! Door Unlocked. 🔓
            </div>
        </section>

        <section class="preview" id="capturePreview">
            <h2>Captured Image</h2>
            <img id="capturedImg" src="" alt="Captured frame">
        </section>
    </main>

    <script>
        const startBtn = document.getElementById('startBtn');
        const stopBtn = document.getElementById('stopBtn');
        const captureBtn = document.getElementById('captureBtn');
        const unlockBtn = document.getElementById('unlockBtn');
        const img = document.getElementById('stream');
        const capturedImg = document.getElementById('capturedImg');
        const previewBox = document.getElementById('capturePreview');
        const accessGrantedAlert = document.getElementById('accessGrantedAlert');

        let streaming = false;

        startBtn.addEventListener('click', () => {
            img.style.display = 'block';
            streaming = true;
            startBtn.disabled = true;
            stopBtn.disabled = false;
            captureBtn.disabled = false;
            unlockBtn.disabled = false;
            accessGrantedAlert.style.display = 'none';
        });

        stopBtn.addEventListener('click', () => {
            img.src = "";
            img.style.display = 'none';
            streaming = false;
            startBtn.disabled = false;
            stopBtn.disabled = true;
            captureBtn.disabled = true;
            unlockBtn.disabled = true;
            accessGrantedAlert.style.display = 'none';
        });

        captureBtn.addEventListener('click', () => {
            if (!streaming) return;
            const canvas = document.createElement('canvas');
            const context = canvas.getContext('2d');
            canvas.width = img.offsetWidth;
            canvas.height = img.offsetHeight;
            context.drawImage(img, 0, 0, canvas.width, canvas.height);
            capturedImg.src = canvas.toDataURL('image/png');
            previewBox.style.display = 'block';
            previewBox.scrollIntoView({ behavior: 'smooth' });
            accessGrantedAlert.style.display = 'none';
        });
        
        unlockBtn.addEventListener('click', () => {
            accessGrantedAlert.style.display = 'block';
            accessGrantedAlert.scrollIntoView({ behavior: 'smooth', block: 'center' });
            setTimeout(() => {
                accessGrantedAlert.style.display = 'none';
            }, 5000); 
        });
    </script>
</body>
</html>
""")
c_array_output = html_to_c_gzip_array(html_input)

print(c_array_output)

